@echo off
setlocal enabledelayedexpansion

rem BAT script that creates the binaries for Carla (carla.org).
rem Run it through a cmd with the x64 Visual C++ Toolset enabled.

set LOCAL_PATH=%~dp0
set FILE_N=-[%~n0]:

rem Print batch params (debug purpose)
echo %FILE_N% [Batch params]: %*

rem ============================================================================
rem -- Parse arguments ---------------------------------------------------------
rem ============================================================================

set BUILD_UE5_EDITOR=false
set LAUNCH_UE5_EDITOR=false
set REMOVE_INTERMEDIATE=false
set USE_CARSIM=false
set USE_CHRONO=false
set CARSIM_STATE="CarSim OFF"
set CHRONO_STATE="Chrono OFF"
set EDITOR_FLAGS=""

:arg-parse
echo %1
if not "%1"=="" (
    if "%1"=="--editor-flags" (
        set EDITOR_FLAGS=%2
        shift
    )
    if "%1"=="--build" (
        set BUILD_UE5_EDITOR=true
    )
    if "%1"=="--launch" (
        set LAUNCH_UE5_EDITOR=true
    )
    if "%1"=="--clean" (
        set REMOVE_INTERMEDIATE=true
    )
    if "%1"=="--carsim" (
        set USE_CARSIM=true
    )
    if "%1"=="--chrono" (
        set USE_CHRONO=true
    )
    if "%1"=="-h" (
        goto help
    )
    if "%1"=="--help" (
        goto help
    )
    shift
    goto arg-parse
)
rem remove quotes from arguments
set EDITOR_FLAGS=%EDITOR_FLAGS:"=%

if %REMOVE_INTERMEDIATE% == false (
    if %LAUNCH_UE5_EDITOR% == false (
        if %BUILD_UE5_EDITOR% == false (
            goto help
        )
    )
)

rem Get Unreal Engine root path
if not defined UE5_ROOT (
    set KEY_NAME="HKEY_LOCAL_MACHINE\SOFTWARE\EpicGames\Unreal Engine"
    set VALUE_NAME=InstalledDirectory
    for /f "usebackq tokens=1,2,*" %%A in (`reg query !KEY_NAME! /s /reg:64`) do (
        if "%%A" == "!VALUE_NAME!" (
            set UE5_ROOT=%%C
        )
    )
    if not defined UE5_ROOT goto error_unreal_no_found
)
if not "%UE5_ROOT:~-1%"=="\" set UE5_ROOT=%UE5_ROOT%\

rem Set the visual studio solution directory
rem
set UE5_PROJECT_FOLDER=%ROOT_PATH:/=\%Unreal\CarlaUE5\
pushd "%UE5_PROJECT_FOLDER%"

rem Clear binaries and intermediates generated by the build system
rem
if %REMOVE_INTERMEDIATE% == true (
    rem Remove directories
    for %%G in (
        "%UE5_PROJECT_FOLDER%Binaries",
        "%UE5_PROJECT_FOLDER%Build",
        "%UE5_PROJECT_FOLDER%Saved",
        "%UE5_PROJECT_FOLDER%Intermediate",
        "%UE5_PROJECT_FOLDER%Plugins\Carla\Binaries",
        "%UE5_PROJECT_FOLDER%Plugins\Carla\Intermediate",
        "%UE5_PROJECT_FOLDER%.vs"
    ) do (
        if exist %%G (
            echo %FILE_N% Cleaning %%G
            rmdir /s/q %%G
        )
    )

    rem Remove files
    for %%G in (
        "%UE5_PROJECT_FOLDER%CarlaUE5.sln"
    ) do (
        if exist %%G (
            echo %FILE_N% Cleaning %%G
            del %%G
        )
    )
)

rem Build Carla Editor
rem

if %USE_CARSIM% == true (
    py -3 %ROOT_PATH%Util/BuildTools/enable_carsim_to_uproject.py -f="%ROOT_PATH%Unreal/CarlaUE5/CarlaUE5.uproject" -e
    set CARSIM_STATE="CarSim ON"
) else (
    py -3 %ROOT_PATH%Util/BuildTools/enable_carsim_to_uproject.py -f="%ROOT_PATH%Unreal/CarlaUE5/CarlaUE5.uproject"
    set CARSIM_STATE="CarSim OFF"
)
if %USE_CHRONO% == true (
    set CHRONO_STATE="Chrono ON"
) else (
    set CHRONO_STATE="Chrono OFF"
)
set OPTIONAL_MODULES_TEXT=%CARSIM_STATE% %CHRONO_STATE%
echo %OPTIONAL_MODULES_TEXT% > "%ROOT_PATH%Unreal/CarlaUE5/Config/OptionalModules.ini"

if %BUILD_UE5_EDITOR% == true (
    echo %FILE_N% Building Unreal Editor...

    call "%UE5_ROOT%Engine\Build\BatchFiles\Build.bat"^
        CarlaUE5Editor^
        Win64^
        Development^
        -WaitMutex^
        -FromMsBuild^
        "%ROOT_PATH%Unreal/CarlaUE5/CarlaUE5.uproject"
    if errorlevel 1 goto bad_exit

    call "%UE5_ROOT%Engine\Build\BatchFiles\Build.bat"^
        CarlaUE5^
        Win64^
        Development^
        -WaitMutex^
        -FromMsBuild^
        "%ROOT_PATH%Unreal/CarlaUE5/CarlaUE5.uproject"
    if errorlevel 1 goto bad_exit
)

rem Launch Carla Editor
rem
if %LAUNCH_UE5_EDITOR% == true (
    echo %FILE_N% Launching Unreal Editor...
    call "%UE5_ROOT%\Engine\Binaries\Win64\UE4Editor.exe"^
        "%UE5_PROJECT_FOLDER%CarlaUE5.uproject" %EDITOR_FLAGS%
    if %errorlevel% neq 0 goto error_build
)

goto good_exit

rem ============================================================================
rem -- Messages and Errors -----------------------------------------------------
rem ============================================================================

:help
    echo Build LibCarla.
    echo "Usage: %FILE_N% [-h^|--help] [--build] [--launch] [--clean]"
    goto good_exit

:error_build
    echo.
    echo %FILE_N% [ERROR] There was a problem building CarlaUE5.
    echo %FILE_N%         Please go to "Carla\Unreal\CarlaUE5", right click on
    echo %FILE_N%         "CarlaUE5.uproject" and select:
    echo %FILE_N%         "Generate Visual Studio project files"
    echo %FILE_N%         Open de generated "CarlaUE5.sln" and try to manually compile it
    echo %FILE_N%         and check what is causing the error.
    goto bad_exit

:good_exit
    endlocal
    exit /b 0

:bad_exit
    endlocal
    exit /b %errorlevel%

:error_unreal_no_found
    echo.
    echo %FILE_N% [ERROR] Unreal Engine not detected
    goto bad_exit
